export const assets = {
  logo: '/assets/siintern-logo-circular-transparent.png',
  bannerWide: '/assets/siintern-banner-3x1.png',
  bannerSocial: '/assets/siintern-banner-1100x520.png',
  hero: '/assets/siintern-hero-character-transparent.png',
  origin: '/assets/siintern-origin-story.png',
  firstDay: '/assets/siintern-first-day.png',
  taskList: '/assets/siintern-task-list.png',
  missionGrid: '/assets/siintern-mission-grid.png',
  aiLab: '/assets/siintern-ai-lab.png',
  robotaxi: '/assets/siintern-robotaxi-mission.png',
  rocket: '/assets/siintern-rocket-mission.png',
  ethereum: '/assets/siintern-ethereum-mission.png',
  army: '/assets/siintern-intern-army.png',
  future: '/assets/siintern-to-the-future.png',
  memeWall: '/assets/siintern-office-meme-wall.png',
} as const;

export const assetSize = {
  logo: { width: 960, height: 960 },
  bannerWide: { width: 1024, height: 341 },
  bannerSocial: { width: 1024, height: 483 },
  hero: { width: 662, height: 1024 },
  origin: { width: 1024, height: 485 },
  firstDay: { width: 1024, height: 341 },
  taskList: { width: 792, height: 995 },
  missionGrid: { width: 1024, height: 682 },
  aiLab: { width: 1024, height: 498 },
  robotaxi: { width: 1024, height: 539 },
  rocket: { width: 1024, height: 341 },
  ethereum: { width: 1024, height: 341 },
  army: { width: 1024, height: 341 },
  future: { width: 1024, height: 341 },
  memeWall: { width: 1024, height: 341 },
} as const;
